[workspace]
members = ["xtask", "crates/*"]
resolver = "2"
default-members = ["crates/core"]

[workspace.dependencies]
fast_levenshtein = { path = "crates/core" }

[profile.release]
lto = true
strip = true
