name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  check:
    runs-on: ${{ matrix.os }}
    name: check (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}

      - name: Prepare
        run: |
          cargo --version
          cargo +stable install just
          cargo +stable install taplo-cli

      - name: Run check
        run: |
          just check

  tests:
    needs: check
    runs-on: ${{ matrix.os }}
    name: tests (${{ matrix.target }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}

      - name: Install just
        run: |
          cargo +stable install just

      - name: Test code
        run: |
          rustup target add ${{ matrix.target }}
          just gtc
          cargo +stable test --target ${{ matrix.target }}
